compiler:
- gcc
notifications:
email:
recipients:
- method_aspect_card@yahoo.co.jp
on_success: change #[always|never|change] # default: change
on_failure: change #[always|never|change] # default: always
script: 
- pwd
- ls
- git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
- export PATH="$HOME/.rbenv/bin:$PATH"
- eval "$(rbenv init -)"
- rbenv --version
- git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
- rbenv install -l
- rbenv install 2.1.3
- rbenv global 2.1.3
- rbenv rehash
- ruby --version
- gem install itamae
- itamae local install_recipe.rb
